language: node_js

node_js:
  - "4"
  - "5"
  - "6"
  - "7"
  - "node"

before_script:
  - npm run build

after_success:
  - npm run coverage
  - npm run coveralls

notifications:
    email: false

deploy:
  provider: npm
  email: hi@thorgate.eu
  api_key:
    secure: >
      jzIuX5jFSi8/6hvUrlnCwgMVsFXVVWs3E8+xpQxPAdZr/Xu08lmjGgBvnUgw+7uwGC9MJS5a7aRHD9Py/lEQZ6MCLAl5tSqNv1r6NQUGvtymq
      7IBc2V28+NKGpQ2vAA+YKcf2oXiiT0aqmTNgSa4DQLXY77GRqmgc/9scw8gt9brGHj5+QCPqLVoJxShmanuk6k2MdojyW92mXfOkoysMO11Kd
      BxJMyvMoKek2tZsgDkSsbYmOi7Hz/bTPVLBzleNtfC1kmIt39g2aSzdZclHRKqQJGml+qnuRq+DU9aqtSs4mkACp7n2HKDHIyAcYBmz5aHDPB
      Bw1FnLm93Ht4+U/O64qy6hZWGci74ag5juXQCbXOw6M/J/Zyjo2M5Zzc3frL4Tu3WL6FfGsdW2TY1jNitlQlqI7TujIffD064+MiTLnuDoDeZ
      6vyOZ32aFs9pLGOe8QmDEDFglAsaUKeuWuF2I72hbP+jwKLMH5W5KWHMLEvoZth4N3cxD1RJaHHCzP4ALE0AMGsgDprshSkpdJ0J0+H73niPD
      /4+EErEnkB0FVYmWynzvMEBH4MAbXFCZj1zbibt6NHZI44n6fvyHX9gpbPg3fuCLpsBNWNkpIQaFvoGsODRo3LmEKZ2rObuArJx4+OE+wOdsG
      2eFZClyuJi/5nJ1fBBAenRS0PBqLg=
  on:
    tags: true
    node: "7"
